name: MATLAB CI

on:
  push:
    branches: [ main ] # Adjust if your default branch is different (e.g., master)
  pull_request:
    branches: [ main ] # Adjust if your default branch is different
  workflow_dispatch:    # Allows manual triggering of the workflow
  
jobs:
  test-and-lint:
    name: Test & Lint (MATLAB ${{ matrix.matlab-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Continue other jobs in matrix even if one fails
      matrix:
        matlab-version: [ R2025a ] # Specify MATLAB version(s)
        # Add more versions to test against, e.g.:
        # matlab-version: [ R2022b, R2023a, R2023b ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-version }}
          products: Image_Processing_Toolbox 

      - name: Run MATLAB Build (Lint & Test)
        uses: matlab-actions/run-build@v2
        with:
          tasks: lint test package # Add the package task

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        if: always() # Always run this step to upload results, even if tests fail
        with:
          name: matlab-test-results-${{ matrix.matlab-version }}
          path: test-results/results.xml

      - name: Upload Toolbox Artifact
        uses: actions/upload-artifact@v4
        if: success() # Only upload if previous steps (including packaging) succeed
        with:
          name: matlab-toolbox-${{ matrix.matlab-version }}
          path: releases/GeometryToolbox.mltbx # Path updated to the releases folder

      # Optional: Upload Code Coverage Artifact
      # - name: Upload Code Coverage Artifact
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: matlab-code-coverage-${{ matrix.matlab-version }}
      #     path: code-coverage/coverage.xml